# add/subtract 5% volume
UP    add volume 5
DOWN  add volume -5

# seek exactly 10 second forward/backward
Shift+RIGHT  seek  10 exact 
Shift+LEFT   seek -10 exact 

# seek exactly 5 seconds forward/backward
RIGHT seek  5  exact 
LEFT  seek -5  exact 

# seek exactly 10 second forward/backward
Shift+RIGHT  seek  10 exact 
Shift+LEFT   seek -10 exact 

# add/subtract 5% volume
UP    add volume 5
DOWN  add volume -5

# Audio volume control with mouse wheel
WHEEL_UP    add volume 5
WHEEL_DOWN   add volume -5

# Speed up increments
] add speed 0.1
[ add speed -0.1  
