# Font type
sub-font='Comic Sans MS'
# Font size
sub-font-size=38
# Font color
sub-color='#FFFFFF'
# Font format  
sub-bold=no
sub-italic=no
# Text background/box (black with 75% alpha) 
	# sub-back-color='#C0000000'
sub-back-color='#00000000'
# Continue from where you left
save-position-on-quit
